### ISSUE TITLE
Problem with Requiring KeyboardJS 

### ISSUE THREAD

**Issue by vcshox** [RobertWHurst/KeyboardJS#106]
I use **npm install** to install this library

However, when I reauire it with **const keyboardJS = require('keyboardjs');** it shows the following error:

project_directory/keyboardjs/lib/keyboard.js:245
    targetElement.attachEvent('on' + eventName, handler);
                 ^

TypeError: Cannot read property 'attachEvent' of undefined
    at Keyboard._bindEvent (/Users/huanglarry/NodeJS/keyboard/node_modules/keyboardjs/lib/keyboard.js:245:18)
    at Keyboard.watch (/Users/huanglarry/NodeJS/keyboard/node_modules/keyboardjs/lib/keyboard.js:178:8)
    at new Keyboard (/Users/huanglarry/NodeJS/keyboard/node_modules/keyboardjs/lib/keyboard.js:24:8)
    at Object.<anonymous> (/Users/huanglarry/NodeJS/keyboard/node_modules/keyboardjs/index.js:6:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

Did I miss anything?

**Comment by RobertWHurst** [comment]
This is because you are trying to run KeyboardJS outside of the browser. It is possible to run keyboardJS in node, but you first have to shim a few methods from the browser. This is out of scope of the lib, but I think I'll prevent this from throwing in node. Instead, you'll have to explicitly set a window object.

**Comment by zachmoss1** [comment]
is there a specific resource that you recommend for finding and using shims that allow for successful operation? i am having a hard time finding ones that qualify.
